docker stop selenium-hub
docker stop selenium-chrome1
docker stop selenium-chrome2
docker stop selenium-chrome3
docker stop selenium-chrome4
docker rm selenium-hub
docker rm selenium-chrome1
docker rm selenium-chrome2
docker rm selenium-chrome3
docker rm selenium-chrome4